import { NanoApiError } from "./types.js";
import {
  type Target,
  VECTOR_DATA_DIR,
  VECTOR_VERSION,
  vectorSink,
} from "./vector.js";

const WINDOWS_DATA_DIR = "C:/ProgramData/Vector/data";

/**
 * Default Windows Event Log channels to collect. Sysmon and Defender are included so a typical
 * security endpoint is covered out of the box; events are split into windows_sysmon vs
 * windows_event by the transform below.
 */
export const DEFAULT_WINDOWS_CHANNELS = [
  "Application",
  "System",
  "Security",
  "Microsoft-Windows-Sysmon/Operational",
  "Microsoft-Windows-PowerShell/Operational",
  "Microsoft-Windows-Windows Defender/Operational",
];

export interface WindowsAgentPlan {
  target: Target;
  channels: string[];
  bufferBytes: number;
}

/**
 * Windows endpoint agent: native windows_event_log collection (stable since Vector 0.55.0),
 * Sysmon split out by channel, shipped to the target over Vector-native. Ports the proven
 * nano-ludus agent config to a standalone artifact.
 */
export function buildWindowsAgentToml(plan: WindowsAgentPlan, generatedAt: string): string {
  const channels = plan.channels.map((c) => `"${c}"`).join(", ");
  return `# nano Windows endpoint agent — generated by @nano-rs/connect on ${generatedAt}
# Collects Windows Event Log (including Sysmon) natively and ships to ${plan.target.host}:${plan.target.port}
# over the Vector-native protocol. Install with install-agent.ps1 (Run as Administrator).

data_dir = "${WINDOWS_DATA_DIR}"

# Note: some Vector builds have a windows_event_log freeze-after-idle bug (vectordotdev/vector
# #25194). The service is configured with automatic restart-on-failure as a safety net.
[sources.windows_events]
type = "windows_event_log"
channels = [${channels}]
read_existing_events = false

[transforms.tag]
type = "remap"
inputs = ["windows_events"]
source = '''
# Sysmon gets its own source_type; everything else is windows_event.
channel = downcase(to_string(.channel) ?? "")
source_type = "windows_event"
if contains(channel, "sysmon") {
    source_type = "windows_sysmon"
}
host = get_hostname!()
event_json = encode_json(.)
. = {}
.message = event_json
.source_type = source_type
.src_host = host
'''

${vectorSink({ name: "out", inputs: ["tag"], target: plan.target, acknowledgements: true, bufferBytes: plan.bufferBytes })}
`;
}

/** PowerShell installer mirroring the nano-ludus role, but pinning a stable MSI (not nightly). */
export function buildWindowsInstaller(): string {
  return `# nano Windows agent installer — run in an elevated PowerShell (Run as Administrator):
#   powershell -ExecutionPolicy Bypass -File .\\install-agent.ps1
$ErrorActionPreference = "Stop"
$ver = "${VECTOR_VERSION}"
$msi = "$env:TEMP\\vector-$ver-x64.msi"
$cfgDir = "C:\\ProgramData\\Vector"
$bin = "C:\\Program Files\\Vector\\bin\\vector.exe"

Write-Host "Downloading Vector $ver..."
Invoke-WebRequest -Uri "https://packages.timber.io/vector/$ver/vector-$ver-x64.msi" -OutFile $msi

# Integrity: the MSI is Authenticode-signed. Verify the signature is valid before installing.
$sig = Get-AuthenticodeSignature $msi
if ($sig.Status -ne "Valid") {
    throw "MSI signature is not valid (status: $($sig.Status)). Aborting."
}
Write-Host "MSI signature OK — signed by: $($sig.SignerCertificate.Subject)"

Write-Host "Installing..."
Start-Process msiexec.exe -ArgumentList "/i \`"$msi\`" /quiet /norestart" -Wait

New-Item -ItemType Directory -Force -Path $cfgDir | Out-Null
Copy-Item -Path ".\\vector.toml" -Destination "$cfgDir\\vector.toml" -Force

# (Re)register the service so it runs with our config, as LocalSystem.
sc.exe stop vector 2>$null | Out-Null
sc.exe delete vector 2>$null | Out-Null
New-Service -Name vector -DisplayName "Vector (nano agent)" -StartupType Automatic \`
  -BinaryPathName "\`"$bin\`" --config-toml \`"$cfgDir\\vector.toml\`""
# Auto-restart on crash/freeze (mitigates windows_event_log freeze-on-idle, vector#25194).
sc.exe failure vector reset= 86400 actions= restart/5000/restart/5000/restart/5000 | Out-Null
Start-Service vector
Write-Host "Vector agent installed and started. Logs: Get-Service vector"
`;
}

export interface LinuxFileGroup {
  /** Vector source/transform id (e.g. "auth"). */
  id: string;
  paths: string[];
  sourceType: string;
}

export interface LinuxAgentPlan {
  target: Target;
  journald: boolean;
  files: LinuxFileGroup[];
  bufferBytes: number;
  image: string;
}

/** Linux endpoint agent: journald and/or file tailing, shipped to the target over Vector-native. */
export function buildLinuxAgentToml(plan: LinuxAgentPlan, generatedAt: string): string {
  // The sink's "*_tag" glob would match nothing (and Vector would fail to load) with no sources.
  if (!plan.journald && plan.files.length === 0) {
    throw new NanoApiError("Linux agent has nothing to collect (enable journald or add files).");
  }
  const blocks: string[] = [];

  if (plan.journald) {
    blocks.push(`[sources.journald]
type = "journald"

[transforms.journald_tag]
type = "remap"
inputs = ["journald"]
source = '''
.source_type = "linux_journald"
.src_host = get_hostname!()
'''`);
  }

  for (const f of plan.files) {
    const includes = f.paths.map((p) => `"${p}"`).join(", ");
    blocks.push(`[sources.${f.id}]
type = "file"
include = [${includes}]

[transforms.${f.id}_tag]
type = "remap"
inputs = ["${f.id}"]
source = '''
.source_type = "${f.sourceType}"
.src_host = get_hostname!()
'''`);
  }

  return `# nano Linux endpoint agent — generated by @nano-rs/connect on ${generatedAt}
# Collects journald / log files and ships to ${plan.target.host}:${plan.target.port} over Vector-native.

data_dir = "${VECTOR_DATA_DIR}"

${blocks.join("\n\n")}

# Forward every tagged source to the target. inputs = ["*_tag"] picks up anything you add above.
${vectorSink({ name: "out", inputs: ["*_tag"], target: plan.target, acknowledgements: true, bufferBytes: plan.bufferBytes })}
`;
}

/** systemd unit for the Linux agent. Runs as root because reading /var/log + journald needs it. */
export function buildLinuxAgentSystemd(): string {
  return `# Install (bare-metal Vector on the endpoint):
#   sudo mkdir -p /etc/nano-agent && sudo cp vector.toml /etc/nano-agent/vector.toml
#   sudo cp nano-agent.service /etc/systemd/system/ && sudo systemctl daemon-reload
#   sudo systemctl enable --now nano-agent
# Requires Vector installed: https://vector.dev/docs/setup/installation/
[Unit]
Description=nano Linux endpoint agent (Vector)
After=network-online.target
Wants=network-online.target

[Service]
# Root so it can read /var/log/* and the system journal.
ExecStart=/usr/bin/vector --config /etc/nano-agent/vector.toml
Restart=on-failure
RestartSec=5
StateDirectory=vector

[Install]
WantedBy=multi-user.target
`;
}
