import type { DeviceType } from "./catalog.js";
import { SYSLOG_CATALOG } from "./catalog.js";
import { renderSyslogDevices } from "./syslog.js";
import { metricsSection, type Target, VECTOR_DATA_DIR, vectorSink } from "./vector.js";

export interface AggregatorPlan {
  /** Port endpoint agents ship to (Vector-native source). */
  agentPort: number;
  /** Syslog devices to also listen for on the aggregator (optional). */
  syslogSelected: DeviceType[];
  nanoHost: string;
  nanoPort: number;
  bufferBytes: number;
  image: string;
}

/**
 * The aggregator pool: receives endpoint agents over Vector-native and (optionally) syslog from
 * network devices, then forwards everything to nano. Generalizes the nano-ludus aggregator role.
 */
export function buildAggregatorToml(plan: AggregatorPlan, generatedAt: string): string {
  const { active, commented } = renderSyslogDevices(plan.syslogSelected);
  const target: Target = { host: plan.nanoHost, port: plan.nanoPort };

  return `# nano aggregator — generated by @nano-rs/connect on ${generatedAt}
#
# Receives endpoint agents (Vector-native) and optionally syslog from network devices, then
# forwards everything to nano at ${plan.nanoHost}:${plan.nanoPort}. Point your Windows/Linux agents
# at this host:${plan.agentPort}; point syslog devices at the per-device ports below.

data_dir = "${VECTOR_DATA_DIR}"

# =============================================================================
# Endpoint agents ship here (already tagged with their source_type)
# =============================================================================
[sources.agents]
type = "vector"
address = "0.0.0.0:${plan.agentPort}"

# =============================================================================
# Syslog from network devices (enabled below; uncomment more as needed)
# =============================================================================
${active || "# (no syslog devices enabled — uncomment one below to listen for it)"}

${commented}

# =============================================================================
# Forward agents + syslog to nano. "agents" is already tagged.${
    plan.syslogSelected.length > 0
      ? ' "*_tag" auto-includes any\n# syslog device you uncomment.'
      : "\n# (Enabling a syslog device below? Add \"*_tag\" to the inputs list so it ships too.)"
  }
# Acks off because syslog (UDP) can't honor them.
# =============================================================================
${vectorSink({
    name: "nano",
    inputs: plan.syslogSelected.length > 0 ? ["agents", "*_tag"] : ["agents"],
    target,
    acknowledgements: false,
    bufferBytes: plan.bufferBytes,
  })}

${metricsSection()}
`;
}

export function buildAggregatorCompose(plan: AggregatorPlan): string {
  const selectedIds = new Set(plan.syslogSelected.map((d) => d.id));
  const syslogPorts = SYSLOG_CATALOG.map((d) => {
    const line = `"${d.port}:${d.port}/${d.mode}"`;
    return selectedIds.has(d.id) ? `      - ${line}` : `      # - ${line}   # ${d.id}`;
  }).join("\n");

  return `# Run the nano aggregator as a container.
#   docker compose up -d
# Point agents at <this-host>:${plan.agentPort}. Enable syslog devices in vector.toml, then
# uncomment their ports below and re-run.
services:
  nano-aggregator:
    image: ${plan.image}
    container_name: nano-aggregator
    restart: unless-stopped
    command: ["--config", "/etc/vector/vector.toml"]
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - nano-aggregator-data:${VECTOR_DATA_DIR}
    ports:
      - "${plan.agentPort}:${plan.agentPort}"   # endpoint agents
${syslogPorts}
      # metrics (9598) stay internal for the healthcheck; uncomment to scrape from the host:
      # - "9598:9598"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:9598/metrics"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  nano-aggregator-data:
`;
}

export function buildAggregatorReadme(plan: AggregatorPlan, generatedAt: string): string {
  const rows = plan.syslogSelected
    .map((d) => `| ${d.label} | \`${d.sourceType}\` | **${d.port}/${d.mode}** |`)
    .join("\n");

  return `# nano aggregator

Generated by \`@nano-rs/connect\` on ${generatedAt}. Forwards to nano at \`${plan.nanoHost}:${plan.nanoPort}\`.

## Run it

\`\`\`bash
docker compose up -d
docker compose logs -f nano-aggregator
\`\`\`

## Point your collectors at it

- **Endpoint agents** (Windows / Linux) ship to **this host : ${plan.agentPort}** (Vector-native).
  Generate them with \`npx @nano-rs/connect add-agent\` and use this host:port as the target.
- **Syslog devices** send to this host on their assigned port:

| Device | source_type | Send syslog to |
| --- | --- | --- |
${rows || "| _(no syslog devices enabled)_ | | |"}

## Confirm data is arriving

\`\`\`bash
npx @nano-rs/connect verify --source <source_type>
\`\`\`
`;
}
