import type { DeviceType } from "./catalog.js";
import { renderSyslogDevices, uplinkLabel } from "./syslog.js";
import { composeUplinkLines, type NanoUplink } from "./uplink.js";
import { httpSinks, metricsSection, VECTOR_DATA_DIR, vectorSink } from "./vector.js";

/** Container name for the aggregator — shared by the compose file and the deploy step. */
export const AGGREGATOR_CONTAINER = "nano-aggregator";

export interface AggregatorPlan {
  /** Port endpoint agents ship to (Vector-native source). */
  agentPort: number;
  /** Every syslog device type this config knows about (curated + selected discovered). */
  syslogCatalog: DeviceType[];
  /** Syslog devices to also listen for on the aggregator (optional). */
  syslogSelected: DeviceType[];
  /** How the aggregator reaches nano. */
  uplink: NanoUplink;
  bufferBytes: number;
  image: string;
}

/**
 * The aggregator pool: receives endpoint agents over Vector-native and (optionally) syslog from
 * network devices, then forwards everything to nano. Generalizes the nano-ludus aggregator role.
 */
/**
 * source_types the generated endpoint agents emit. The HTTP uplink needs one sink per
 * source_type (nano routes on a static per-sink request header), so the aggregator has to know
 * them up front. Keep in sync with the transforms in `agent.ts`.
 */
export const AGENT_SOURCE_TYPES = [
  "windows_event",
  "windows_sysmon",
  "linux_journald",
  "linux_sysmon",
] as const;

/**
 * Fan the pre-tagged agent stream out by source_type so each one can get its own HTTP sink.
 * Only needed on the HTTP path; the native uplink carries source_type per-event.
 */
function agentRouteSection(): string {
  const routes = AGENT_SOURCE_TYPES.map((st) => `${st} = '.source_type == "${st}"'`).join("\n");
  return `# The HTTP uplink needs one sink per source_type, so split the agent stream by tag.
# An agent source_type NOT listed here lands in "_unmatched", which nothing consumes — Vector
# drops it. That is deliberate: dropping is visible in metrics, whereas routing it to a sink with
# the wrong X-Source-Type header would silently mislabel your data. Add a route + matching sink
# below for any custom source_type you introduce (e.g. a --files group on a Linux agent).
[transforms.agent_route]
type = "route"
inputs = ["agents"]

[transforms.agent_route.route]
${routes}`;
}

export function buildAggregatorToml(plan: AggregatorPlan, generatedAt: string): string {
  const { active, commented } = renderSyslogDevices(plan.syslogCatalog, plan.syslogSelected);

  const uplinkSection =
    plan.uplink.transport === "native"
      ? vectorSink({
          name: "nano",
          inputs: plan.syslogSelected.length > 0 ? ["agents", "*_tag"] : ["agents"],
          target: plan.uplink.target,
          acknowledgements: false,
          bufferBytes: plan.bufferBytes,
          tls: plan.uplink.tls,
        })
      : [
          agentRouteSection(),
          "",
          httpSinks(
            [
              ...AGENT_SOURCE_TYPES.map((st) => ({
                sourceType: st,
                inputs: [`agent_route.${st}`],
              })),
              ...plan.syslogSelected.map((d) => ({
                sourceType: d.sourceType,
                inputs: [`${d.id}_tag`],
              })),
            ],
            plan.uplink.ingestUrl,
            plan.bufferBytes,
          ),
        ].join("\n");

  return `# nano aggregator — generated by @nano-rs/connect on ${generatedAt}
#
# Receives endpoint agents (Vector-native) and optionally syslog from network devices, then
# forwards everything to nano — ${uplinkLabel(plan.uplink)}. Point your Windows/Linux agents
# at this host:${plan.agentPort}; point syslog devices at the per-device ports below.

data_dir = "${VECTOR_DATA_DIR}"

# =============================================================================
# Endpoint agents ship here (already tagged with their source_type)
# =============================================================================
[sources.agents]
type = "vector"
address = "0.0.0.0:${plan.agentPort}"

# =============================================================================
# Syslog from network devices (enabled below; uncomment more as needed)
# =============================================================================
${active || "# (no syslog devices enabled — uncomment one below to listen for it)"}

${commented}

# =============================================================================
# Forward agents + syslog to nano. "agents" is already tagged.${
    plan.uplink.transport === "native"
      ? plan.syslogSelected.length > 0
        ? ' "*_tag" auto-includes any\n# syslog device you uncomment.'
        : "\n# (Enabling a syslog device below? Add \"*_tag\" to the inputs list so it ships too.)"
      : "\n# HTTP transport: one sink per source_type (nano routes on a static per-sink header)."
  }
# Acks off because syslog (UDP) can't honor them.
# =============================================================================
${uplinkSection}

${metricsSection()}
`;
}

export function buildAggregatorCompose(plan: AggregatorPlan): string {
  const selectedIds = new Set(plan.syslogSelected.map((d) => d.id));
  const syslogPorts = plan.syslogCatalog
    .map((d) => {
      const line = `"${d.port}:${d.port}/${d.mode}"`;
      return selectedIds.has(d.id) ? `      - ${line}` : `      # - ${line}   # ${d.id}`;
    })
    .join("\n");

  const { env, volumes } = composeUplinkLines(plan.uplink);

  return `# Run the nano aggregator as a container.
#   docker compose up -d
# Point agents at <this-host>:${plan.agentPort}. Enable syslog devices in vector.toml, then
# uncomment their ports below and re-run.
services:
  nano-aggregator:
    image: ${plan.image}
    container_name: ${AGGREGATOR_CONTAINER}
    restart: unless-stopped
    command: ["--config", "/etc/vector/vector.toml"]
${env}    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
${volumes}      - nano-aggregator-data:${VECTOR_DATA_DIR}
    ports:
      - "${plan.agentPort}:${plan.agentPort}"   # endpoint agents
${syslogPorts}
      # metrics (9598) stay internal for the healthcheck; uncomment to scrape from the host:
      # - "9598:9598"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:9598/metrics"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  nano-aggregator-data:
`;
}

export function buildAggregatorReadme(plan: AggregatorPlan, generatedAt: string): string {
  const rows = plan.syslogSelected
    .map((d) => `| ${d.label} | \`${d.sourceType}\` | **${d.port}/${d.mode}** |`)
    .join("\n");

  return `# nano aggregator

Generated by \`@nano-rs/connect\` on ${generatedAt}. Forwards to nano — ${uplinkLabel(plan.uplink)}.${
    plan.uplink.transport === "http"
      ? `\n\nThe ingest token is in \`.env\` (0600) beside this file, read as \`\${VECTOR_AUTH_TOKEN}\`.
Each source_type has its own sink because nano routes on the \`X-Source-Type\` request header;
agent source types not listed in \`[transforms.agent_route.route]\` are dropped rather than
mislabeled, so add a route + sink for any custom one.`
      : ""
  }

## Run it

\`\`\`bash
docker compose up -d
docker compose logs -f nano-aggregator
\`\`\`

## Point your collectors at it

- **Endpoint agents** (Windows / Linux) ship to **this host : ${plan.agentPort}** (Vector-native).
  Generate them with \`npx @nano-rs/connect add-agent\` and use this host:port as the target.
- **Syslog devices** send to this host on their assigned port:

| Device | source_type | Send syslog to |
| --- | --- | --- |
${rows || "| _(no syslog devices enabled)_ | | |"}

## Confirm data is arriving

\`\`\`bash
npx @nano-rs/connect verify --source <source_type>
\`\`\`
`;
}
