import type { DeviceType } from "./catalog.js";
import { SYSLOG_CATALOG } from "./catalog.js";
import { commentOut, metricsSection, type Target, VECTOR_DATA_DIR, vectorSink } from "./vector.js";

/** Container name for the syslog collector — shared by the compose file and the deploy step. */
export const COLLECTOR_CONTAINER = "nano-collector";

export interface SyslogPlan {
  /** Devices the operator chose to enable now (rendered active). */
  selected: DeviceType[];
  /** nano's Vector-native endpoint (the `vector` source, default :6000). */
  nanoHost: string;
  nanoPort: number;
  /** Disk buffer size in bytes for the sink. */
  bufferBytes: number;
  /** Container image for the docker-compose artifact. */
  image: string;
}

/** One device's source + source_type-stamping transform. */
function deviceBlock(d: DeviceType): string {
  return `[sources.${d.id}]
type = "syslog"
address = "0.0.0.0:${d.port}"
mode = "${d.mode}"

[transforms.${d.id}_tag]
type = "remap"
inputs = ["${d.id}"]
source = '''
# Stamp nano's source_type, overwriting Vector's built-in source_type = "syslog".
host = to_string(.host) ?? ""
event_json = encode_json(.)
. = {}
.message = event_json
.source_type = "${d.sourceType}"
.src_host = host
'''`;
}

/**
 * Render the syslog device catalog: selected devices active, the rest commented-out for later.
 * Shared by the standalone syslog collector and the aggregator (which also listens for syslog).
 */
export function renderSyslogDevices(selected: DeviceType[]): { active: string; commented: string } {
  const selectedIds = new Set(selected.map((d) => d.id));
  const active = SYSLOG_CATALOG.filter((d) => selectedIds.has(d.id))
    .map((d) => `# --- ${d.label} (${d.mode} :${d.port}) ---\n${deviceBlock(d)}`)
    .join("\n\n");
  const commented = SYSLOG_CATALOG.filter((d) => !selectedIds.has(d.id))
    .map((d) => {
      const header = `# --- ${d.label} (${d.mode} :${d.port}) — uncomment to enable ---`;
      const note = d.note ? `# note: ${d.note}\n` : "";
      return `${header}\n${note}${commentOut(deviceBlock(d))}`;
    })
    .join("\n\n");
  return { active, commented };
}

export function buildVectorToml(plan: SyslogPlan, generatedAt: string): string {
  const { active, commented } = renderSyslogDevices(plan.selected);
  const target: Target = { host: plan.nanoHost, port: plan.nanoPort };

  // A sink whose input glob matches nothing fails to load, so when no device is enabled we ship
  // the sink commented-out (the metrics chain keeps the file valid) with instructions.
  const sink = vectorSink({ name: "nano", inputs: ["*_tag"], target, acknowledgements: false, bufferBytes: plan.bufferBytes });
  const sinkSection =
    plan.selected.length > 0
      ? sink
      : `# No device enabled yet — uncomment one above, then uncomment this sink to start forwarding.\n${commentOut(sink)}`;

  return `# Vector edge collector for nano — generated by @nano-rs/connect on ${generatedAt}
#
# Collects syslog from your devices and forwards to nano over the Vector-native protocol
# (protobuf + end-to-end acknowledgements + disk buffering — more reliable than HTTP).
#
# To enable more device types: uncomment its block below. The sink input glob "*_tag" picks it
# up automatically — no need to edit the sink. To add a vendor that isn't listed, copy a block
# and change the id, port, mode, and source_type.

data_dir = "${VECTOR_DATA_DIR}"

# =============================================================================
# Enabled listeners
# =============================================================================
${active || "# (none selected — uncomment a device below to start collecting)"}

# =============================================================================
# More device types — uncomment what you need (each gets its own port)
# =============================================================================
${commented}

# =============================================================================
# Sink: forward everything tagged above to nano (Vector-native :${plan.nanoPort}).
# inputs = ["*_tag"] auto-includes any device block you uncomment. Acks are off because syslog
# (UDP) can't honor them; the disk buffer provides durability across restarts.
# =============================================================================
${sinkSection}

# =============================================================================
# Local metrics (http://localhost:9598/metrics) — handy to confirm events flow
# =============================================================================
${metricsSection()}
`;
}

export function buildDockerCompose(plan: SyslogPlan): string {
  const selectedIds = new Set(plan.selected.map((d) => d.id));
  // List every catalog port; comment the ones not enabled so uncommenting stays symmetric with
  // vector.toml (enable a device there -> uncomment its port here -> re-run).
  const ports = SYSLOG_CATALOG.map((d) => {
    const line = `"${d.port}:${d.port}/${d.mode}"`;
    return selectedIds.has(d.id)
      ? `      - ${line}`
      : `      # - ${line}   # ${d.id}`;
  }).join("\n");

  return `# Run the nano edge collector as a container.
#   docker compose up -d
# Edit vector.toml to enable more device types, then add their ports below and re-run.
services:
  nano-collector:
    image: ${plan.image}
    container_name: ${COLLECTOR_CONTAINER}
    restart: unless-stopped
    command: ["--config", "/etc/vector/vector.toml"]
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - nano-collector-data:${VECTOR_DATA_DIR}
    ports:
${ports}
      # metrics (9598) stay internal for the healthcheck; uncomment to scrape from the host:
      # - "9598:9598"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:9598/metrics"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  nano-collector-data:
`;
}

export function buildSystemdUnit(): string {
  return `# Install (bare-metal Vector, not Docker):
#   sudo mkdir -p /etc/nano-collector && sudo cp vector.toml /etc/nano-collector/vector.toml
#   sudo cp nano-collector.service /etc/systemd/system/
#   sudo systemctl daemon-reload && sudo systemctl enable --now nano-collector
# Requires Vector installed: https://vector.dev/docs/setup/installation/
[Unit]
Description=nano edge collector (Vector)
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/bin/vector --config /etc/nano-collector/vector.toml
Restart=on-failure
RestartSec=5
# Lets Vector bind the unprivileged 55xx syslog ports without running as root.
DynamicUser=true
StateDirectory=vector

[Install]
WantedBy=multi-user.target
`;
}

export function buildReadme(plan: SyslogPlan, generatedAt: string): string {
  const rows = plan.selected
    .map((d) => `| ${d.label} | \`${d.sourceType}\` | **${d.port}/${d.mode}** |`)
    .join("\n");

  return `# nano edge collector — syslog

Generated by \`@nano-rs/connect\` on ${generatedAt}. Forwards to nano at \`${plan.nanoHost}:${plan.nanoPort}\` (Vector-native).

## 1. Run the collector

**Docker (simplest):**
\`\`\`bash
docker compose up -d
docker compose logs -f nano-collector
\`\`\`

**systemd (bare metal):** see the header of \`nano-collector.service\`.

## 2. Point your devices at it

Send each device's syslog to **this machine's IP** on its assigned port:

| Device | source_type | Send syslog to |
| --- | --- | --- |
${rows || "| _(none enabled yet)_ | | |"}

Replace "this machine's IP" with the collector host's address reachable from your devices.

## 3. Enable more device types

Uncomment the device's block in \`vector.toml\` (the sink picks it up automatically), expose its
port in \`docker-compose.yml\`, and re-run \`docker compose up -d\`.

## 4. Confirm data is arriving

\`\`\`bash
npx @nano-rs/connect verify --source <source_type>
\`\`\`

Events become fully searchable once nano has a parser for that source_type; until then they're
ingested but parse generically.
`;
}
