import type { DeviceType } from "./catalog.js";
import { SYSLOG_CATALOG } from "./catalog.js";

export interface SyslogPlan {
  /** Devices the operator chose to enable now (rendered active). */
  selected: DeviceType[];
  /** nano's Vector-native endpoint (the `vector` source, default :6000). */
  nanoHost: string;
  nanoPort: number;
  /** Disk buffer size in bytes for the sink. */
  bufferBytes: number;
  /** Container image for the docker-compose artifact. */
  image: string;
}

const VECTOR_DATA_DIR = "/var/lib/vector";

/** One device's source + source_type-stamping transform. */
function deviceBlock(d: DeviceType): string {
  return `[sources.${d.id}]
type = "syslog"
address = "0.0.0.0:${d.port}"
mode = "${d.mode}"

[transforms.${d.id}_tag]
type = "remap"
inputs = ["${d.id}"]
source = '''
# Stamp nano's source_type, overwriting Vector's built-in source_type = "syslog".
host = to_string(.host) ?? ""
event_json = encode_json(.)
. = {}
.message = event_json
.source_type = "${d.sourceType}"
.src_host = host
'''`;
}

/** Prefix every line with "# " so a whole block can be shipped commented-out. */
function commentOut(text: string): string {
  return text
    .split("\n")
    .map((line) => (line.length ? `# ${line}` : "#"))
    .join("\n");
}

export function buildVectorToml(plan: SyslogPlan, generatedAt: string): string {
  const selectedIds = new Set(plan.selected.map((d) => d.id));

  const active = SYSLOG_CATALOG.filter((d) => selectedIds.has(d.id))
    .map((d) => `# --- ${d.label} (${d.mode} :${d.port}) ---\n${deviceBlock(d)}`)
    .join("\n\n");

  const catalog = SYSLOG_CATALOG.filter((d) => !selectedIds.has(d.id))
    .map((d) => {
      const header = `# --- ${d.label} (${d.mode} :${d.port}) — uncomment to enable ---`;
      const note = d.note ? `# note: ${d.note}\n` : "";
      return `${header}\n${note}${commentOut(deviceBlock(d))}`;
    })
    .join("\n\n");

  return `# Vector edge collector for nano — generated by @nano-rs/connect on ${generatedAt}
#
# Collects syslog from your devices and forwards to nano over the Vector-native protocol
# (protobuf + end-to-end acknowledgements + disk buffering — more reliable than HTTP).
#
# To enable more device types: uncomment its block below. The sink input glob "*_tag" picks it
# up automatically — no need to edit the sink. To add a vendor that isn't listed, copy a block
# and change the id, port, mode, and source_type.

data_dir = "${VECTOR_DATA_DIR}"

# =============================================================================
# Enabled listeners
# =============================================================================
${active || "# (none selected — uncomment a device below to start collecting)"}

# =============================================================================
# More device types — uncomment what you need (each gets its own port)
# =============================================================================
${catalog}

# =============================================================================
# Sink: forward everything tagged above to nano (Vector-native :${plan.nanoPort})
# inputs = ["*_tag"] auto-includes any device block you uncomment.
# =============================================================================
[sinks.nano]
type = "vector"
inputs = ["*_tag"]
address = "${plan.nanoHost}:${plan.nanoPort}"
# Syslog sources can't honor end-to-end acknowledgements (UDP is fire-and-forget), so we leave
# them off and rely on the disk buffer below for durability across collector restarts.
acknowledgements.enabled = false

[sinks.nano.buffer]
type = "disk"
max_size = ${plan.bufferBytes}
when_full = "block"

# =============================================================================
# Local metrics (http://localhost:9598/metrics) — handy to confirm events flow
# =============================================================================
[sources.internal_metrics]
type = "internal_metrics"

[sinks.metrics]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"
`;
}

export function buildDockerCompose(plan: SyslogPlan): string {
  const ports = plan.selected
    .map((d) => `      - "${d.port}:${d.port}/${d.mode}"`)
    .join("\n");

  return `# Run the nano edge collector as a container.
#   docker compose up -d
# Edit vector.toml to enable more device types, then add their ports below and re-run.
services:
  nano-collector:
    image: ${plan.image}
    container_name: nano-collector
    restart: unless-stopped
    command: ["--config", "/etc/vector/vector.toml"]
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - nano-collector-data:${VECTOR_DATA_DIR}
    ports:
${ports || '      # - "5514:5514/udp"   # enable a device in vector.toml, then expose its port here'}
      - "9598:9598"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9598/metrics"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  nano-collector-data:
`;
}

export function buildSystemdUnit(): string {
  return `# Install (bare-metal Vector, not Docker):
#   sudo mkdir -p /etc/nano-collector && sudo cp vector.toml /etc/nano-collector/vector.toml
#   sudo cp nano-collector.service /etc/systemd/system/
#   sudo systemctl daemon-reload && sudo systemctl enable --now nano-collector
# Requires Vector installed: https://vector.dev/docs/setup/installation/
[Unit]
Description=nano edge collector (Vector)
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/bin/vector --config /etc/nano-collector/vector.toml
Restart=on-failure
RestartSec=5
# Lets Vector bind the unprivileged 55xx syslog ports without running as root.
DynamicUser=true
StateDirectory=vector

[Install]
WantedBy=multi-user.target
`;
}

export function buildReadme(plan: SyslogPlan, generatedAt: string): string {
  const rows = plan.selected
    .map((d) => `| ${d.label} | \`${d.sourceType}\` | **${d.port}/${d.mode}** |`)
    .join("\n");

  return `# nano edge collector — syslog

Generated by \`@nano-rs/connect\` on ${generatedAt}. Forwards to nano at \`${plan.nanoHost}:${plan.nanoPort}\` (Vector-native).

## 1. Run the collector

**Docker (simplest):**
\`\`\`bash
docker compose up -d
docker compose logs -f nano-collector
\`\`\`

**systemd (bare metal):** see the header of \`nano-collector.service\`.

## 2. Point your devices at it

Send each device's syslog to **this machine's IP** on its assigned port:

| Device | source_type | Send syslog to |
| --- | --- | --- |
${rows || "| _(none enabled yet)_ | | |"}

Replace "this machine's IP" with the collector host's address reachable from your devices.

## 3. Enable more device types

Uncomment the device's block in \`vector.toml\` (the sink picks it up automatically), expose its
port in \`docker-compose.yml\`, and re-run \`docker compose up -d\`.

## 4. Confirm data is arriving

\`\`\`bash
npx @nano-rs/connect verify --source <source_type>
\`\`\`

Events become fully searchable once nano has a parser for that source_type; until then they're
ingested but parse generically.
`;
}
